// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBomC5-yAZQdQbbigRlWmoSMN0_oG3lduU',
    appId: '1:921089098894:web:c94bd37e9814ae457b35df',
    messagingSenderId: '921089098894',
    projectId: 'mamai-makhrap',
    authDomain: 'mamai-makhrap.firebaseapp.com',
    storageBucket: 'mamai-makhrap.appspot.com',
    measurementId: 'G-025MD3JV4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACL5yvvHxeBmSg5oeOwnQBUIqoQYIQbb0',
    appId: '1:921089098894:android:d12867f95cbc06147b35df',
    messagingSenderId: '921089098894',
    projectId: 'mamai-makhrap',
    storageBucket: 'mamai-makhrap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQ7hju5FWAyPNTrAUFJhM2biudkTe5x8',
    appId: '1:921089098894:ios:0e781b2ee6d222117b35df',
    messagingSenderId: '921089098894',
    projectId: 'mamai-makhrap',
    storageBucket: 'mamai-makhrap.appspot.com',
    iosClientId: '921089098894-4lgtcmuabedalv1bou37vmo0v5ji1r50.apps.googleusercontent.com',
    iosBundleId: 'com.example.mamaimakhrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmQ7hju5FWAyPNTrAUFJhM2biudkTe5x8',
    appId: '1:921089098894:ios:0e781b2ee6d222117b35df',
    messagingSenderId: '921089098894',
    projectId: 'mamai-makhrap',
    storageBucket: 'mamai-makhrap.appspot.com',
    iosClientId: '921089098894-4lgtcmuabedalv1bou37vmo0v5ji1r50.apps.googleusercontent.com',
    iosBundleId: 'com.example.mamaimakhrap',
  );
}
