// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcxDyltr8br-fA2keTKFYd8JRaqDu4FM',
    appId: '1:372808837483:web:d717d6ee984131ee98442e',
    messagingSenderId: '372808837483',
    projectId: 'mamaimakrup',
    authDomain: 'mamaimakrup.firebaseapp.com',
    storageBucket: 'mamaimakrup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcgwjK2l1VXdHlPa119KqDM3RPLiLmCxw',
    appId: '1:372808837483:android:b54341695ca7bd1698442e',
    messagingSenderId: '372808837483',
    projectId: 'mamaimakrup',
    storageBucket: 'mamaimakrup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsgUG4xeQXbSK2fUwNhwdxMrQBvPI9VsA',
    appId: '1:372808837483:ios:9ae793cc59d24ddc98442e',
    messagingSenderId: '372808837483',
    projectId: 'mamaimakrup',
    storageBucket: 'mamaimakrup.appspot.com',
    iosClientId: '372808837483-fu8g9sonsvk2b5a1qo842v5hom4rf3vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mamaimakhrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsgUG4xeQXbSK2fUwNhwdxMrQBvPI9VsA',
    appId: '1:372808837483:ios:9ae793cc59d24ddc98442e',
    messagingSenderId: '372808837483',
    projectId: 'mamaimakrup',
    storageBucket: 'mamaimakrup.appspot.com',
    iosClientId: '372808837483-fu8g9sonsvk2b5a1qo842v5hom4rf3vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mamaimakhrap',
  );
}
